// Fetches SRD 5.1 spells from the Open5e API (document__slug=wotc-srd)
// and regenerates client/src/data/spells.ts.
//
// Open5e wotc-srd content is SRD 5.1 by Wizards of the Coast LLC, released
// under CC BY 4.0 — redistributable with attribution.
//
// Run: npx tsx scripts/import-srd-spells.ts

import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

interface Open5eSpell {
  slug: string
  name: string
  desc: string
  higher_level?: string | null
  range: string
  components: string
  material?: string | null
  ritual: string | boolean
  duration: string
  concentration: string | boolean
  casting_time: string
  level: string            // e.g. "3rd-level"
  level_int: number
  school: string
  dnd_class: string        // comma-separated
  document__slug: string
}
interface Open5ePage<T> { count: number; next: string | null; results: T[] }

interface Spell {
  slug: string
  name: string
  level: number
  school: string
  castingTime: string
  range: string
  components: string
  material?: string
  duration: string
  concentration: boolean
  ritual: boolean
  description: string
  higherLevel?: string
  classes: string[]
}

function toBool(v: string | boolean | undefined): boolean {
  if (typeof v === 'boolean') return v
  if (!v) return false
  return /^(yes|true)/i.test(v)
}

function classList(raw: string): string[] {
  if (!raw) return []
  return raw.split(/,\s*/).map(s => s.trim()).filter(Boolean)
}

function convert(s: Open5eSpell): Spell {
  const out: Spell = {
    slug: s.slug,
    name: s.name,
    level: s.level_int ?? 0,
    school: (s.school ?? '').toLowerCase(),
    castingTime: s.casting_time?.trim() ?? '',
    range: s.range?.trim() ?? '',
    components: s.components?.trim() ?? '',
    material: s.material?.trim() || undefined,
    duration: s.duration?.trim() ?? '',
    concentration: toBool(s.concentration),
    ritual: toBool(s.ritual),
    description: (s.desc ?? '').trim(),
    higherLevel: s.higher_level?.trim() || undefined,
    classes: classList(s.dnd_class),
  }
  if (out.material === undefined) delete (out as Partial<Spell>).material
  if (out.higherLevel === undefined) delete (out as Partial<Spell>).higherLevel
  return out
}

async function fetchAll(): Promise<Open5eSpell[]> {
  const collected: Open5eSpell[] = []
  let url: string | null =
    'https://api.open5e.com/v1/spells/?document__slug=wotc-srd&limit=200&ordering=slug'
  while (url) {
    process.stdout.write(`  → ${url}\n`)
    const res = await fetch(url)
    if (!res.ok) throw new Error(`Open5e ${res.status} ${res.statusText}`)
    const page = await res.json() as Open5ePage<Open5eSpell>
    collected.push(...page.results)
    url = page.next
  }
  return collected
}

function emit(spells: Spell[]): string {
  return `// AUTO-GENERATED by scripts/import-srd-spells.ts — do not edit by hand.
// Source: Open5e (https://api.open5e.com/v1/spells/?document__slug=wotc-srd).
// Content: System Reference Document 5.1 by Wizards of the Coast LLC,
// released under the Creative Commons Attribution 4.0 International License.
// https://creativecommons.org/licenses/by/4.0/

import type { Spell, SourceMetadata } from '@/types'

export const SRD_SOURCE: SourceMetadata = {
  sourceId: 'SRD_5_1',
  sourceName: 'System Reference Document 5.1',
  sourceType: 'SRD_5_1_CC',
  licenseName: 'CC BY 4.0',
  licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  attributionText:
    'This work includes material taken from the System Reference Document 5.1 ("SRD 5.1") by Wizards of the Coast LLC, available under the CC BY 4.0 license.',
  isRedistributable: true,
}

type RawSpell = Omit<Spell, 'source'>

const RAW: RawSpell[] = ${JSON.stringify(spells, null, 2)}

export const SPELLS: Spell[] = RAW.map(s => ({ ...s, source: SRD_SOURCE }))
`
}

async function main() {
  const here = dirname(fileURLToPath(import.meta.url))
  const outPath = join(here, '..', 'client', 'src', 'data', 'spells.ts')

  console.log('Fetching SRD spells from Open5e…')
  const raw = await fetchAll()
  console.log(`  ${raw.length} entries received.`)

  const spells = raw.map(convert).sort((a, b) => a.slug.localeCompare(b.slug))

  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, emit(spells), 'utf-8')
  console.log(`Wrote ${spells.length} spells → ${outPath}`)
}

main().catch(e => { console.error(e); process.exit(1) })
