// Fetches SRD 5.1 items from Open5e (document__slug=wotc-srd) and regenerates
// client/src/data/items.ts. Covers three endpoints:
//   /magicitems/ — magic items (~237)
//   /weapons/    — mundane weapons (~37)
//   /armor/      — mundane armor (~18)
// Open5e v1 has no /equipment/ endpoint, so adventuring gear (rope, rations,
// torches, tools) is not included; if you want those, the only public source
// is 5etools' data/items-base.json, which needs its own converter.
//
// Output: ~292 entries, all sharing the Combatr MagicItem shape with a
// `magic: boolean` flag. Mundane weapons/armor get magic=false; magic items
// get magic=true. Source is SRD 5.1 by Wizards of the Coast LLC, CC BY 4.0.
//
// Run: npx tsx scripts/import-srd-items.ts

import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

interface Open5ePage<T> { count: number; next: string | null; results: T[] }

interface Open5eMagicItem {
  slug: string
  name: string
  type: string
  desc: string
  rarity: string
  requires_attunement?: string | null
}

interface Open5eWeapon {
  slug: string
  name: string
  category: string
  cost?: string
  damage_dice?: string
  damage_type?: string
  weight?: string
  properties?: string[]
}

interface Open5eArmor {
  slug: string
  name: string
  category: string
  ac_string?: string
  strength_requirement?: number | null
  cost?: string
  weight?: string
  stealth_disadvantage?: boolean
}

interface RawItem {
  slug: string
  name: string
  type: string
  rarity: string
  requiresAttunement: boolean
  attunementText?: string
  description: string
  magic: boolean
}

// ── converters ───────────────────────────────────────────────────────

function convertMagicItem(i: Open5eMagicItem): RawItem {
  const attText = (i.requires_attunement ?? '').trim()
  const out: RawItem = {
    slug: i.slug,
    name: i.name,
    type: (i.type ?? '').trim(),
    rarity: (i.rarity ?? '').trim().toLowerCase() || 'varies',
    requiresAttunement: attText.length > 0,
    attunementText: attText || undefined,
    description: (i.desc ?? '').trim(),
    magic: true,
  }
  if (out.attunementText === undefined) delete out.attunementText
  return out
}

function convertWeapon(w: Open5eWeapon): RawItem {
  const lines: string[] = []
  if (w.damage_dice || w.damage_type) {
    const dd = (w.damage_dice ?? '').trim()
    const dt = (w.damage_type ?? '').trim()
    lines.push(`Damage: ${[dd, dt].filter(Boolean).join(' ')}`.trim())
  }
  if (w.cost)   lines.push(`Cost: ${w.cost}`)
  if (w.weight) lines.push(`Weight: ${w.weight}`)
  if (w.properties && w.properties.length) lines.push(`Properties: ${w.properties.join(', ')}`)
  return {
    slug: w.slug,
    name: w.name,
    type: (w.category ?? 'Weapon').trim(),
    rarity: 'mundane',
    requiresAttunement: false,
    description: lines.join('\n'),
    magic: false,
  }
}

function convertArmor(a: Open5eArmor): RawItem {
  const lines: string[] = []
  if (a.ac_string) lines.push(`AC: ${a.ac_string}`)
  if (a.strength_requirement) lines.push(`Strength requirement: ${a.strength_requirement}`)
  if (a.cost)   lines.push(`Cost: ${a.cost}`)
  if (a.weight) lines.push(`Weight: ${a.weight}`)
  if (a.stealth_disadvantage) lines.push('Stealth: disadvantage')
  return {
    slug: a.slug,
    name: a.name,
    type: (a.category ?? 'Armor').trim(),
    rarity: 'mundane',
    requiresAttunement: false,
    description: lines.join('\n'),
    magic: false,
  }
}

// ── fetchers ─────────────────────────────────────────────────────────

async function fetchAll<T>(endpoint: string): Promise<T[]> {
  const collected: T[] = []
  let url: string | null =
    `https://api.open5e.com/v1/${endpoint}/?document__slug=wotc-srd&limit=200&ordering=slug`
  while (url) {
    process.stdout.write(`  → ${url}\n`)
    const res = await fetch(url)
    if (!res.ok) throw new Error(`Open5e /${endpoint}/ ${res.status} ${res.statusText}`)
    const page = await res.json() as Open5ePage<T>
    collected.push(...page.results)
    url = page.next
  }
  return collected
}

// ── emit ─────────────────────────────────────────────────────────────

function emit(items: RawItem[]): string {
  return `// AUTO-GENERATED by scripts/import-srd-items.ts — do not edit by hand.
// Sources:
//   https://api.open5e.com/v1/magicitems/?document__slug=wotc-srd
//   https://api.open5e.com/v1/weapons/?document__slug=wotc-srd
//   https://api.open5e.com/v1/armor/?document__slug=wotc-srd
// Content: System Reference Document 5.1 by Wizards of the Coast LLC,
// released under the Creative Commons Attribution 4.0 International License.
// https://creativecommons.org/licenses/by/4.0/

import type { MagicItem, SourceMetadata } from '@/types'

export const SRD_SOURCE: SourceMetadata = {
  sourceId: 'SRD_5_1',
  sourceName: 'System Reference Document 5.1',
  sourceType: 'SRD_5_1_CC',
  licenseName: 'CC BY 4.0',
  licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
  attributionText:
    'This work includes material taken from the System Reference Document 5.1 ("SRD 5.1") by Wizards of the Coast LLC, available under the CC BY 4.0 license.',
  isRedistributable: true,
}

type RawItem = Omit<MagicItem, 'source'>

const RAW: RawItem[] = ${JSON.stringify(items, null, 2)}

export const ITEMS: MagicItem[] = RAW.map(i => ({ ...i, source: SRD_SOURCE }))
`
}

// ── main ─────────────────────────────────────────────────────────────

async function main() {
  const here = dirname(fileURLToPath(import.meta.url))
  const outPath = join(here, '..', 'client', 'src', 'data', 'items.ts')

  console.log('Fetching SRD magic items from Open5e…')
  const magic = await fetchAll<Open5eMagicItem>('magicitems')
  console.log(`  ${magic.length} magic items.`)

  console.log('Fetching SRD weapons…')
  const weapons = await fetchAll<Open5eWeapon>('weapons')
  console.log(`  ${weapons.length} weapons.`)

  console.log('Fetching SRD armor…')
  const armor = await fetchAll<Open5eArmor>('armor')
  console.log(`  ${armor.length} armor entries.`)

  const items: RawItem[] = [
    ...magic.map(convertMagicItem),
    ...weapons.map(convertWeapon),
    ...armor.map(convertArmor),
  ].sort((a, b) => a.slug.localeCompare(b.slug))

  // De-dup by slug (last wins) in case any endpoint overlaps with another.
  const dedup = new Map<string, RawItem>()
  for (const i of items) dedup.set(i.slug, i)
  const final = [...dedup.values()].sort((a, b) => a.slug.localeCompare(b.slug))

  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, emit(final), 'utf-8')
  console.log(`Wrote ${final.length} items → ${outPath}`)
}

main().catch(e => { console.error(e); process.exit(1) })
